# Generated by Django 6.0.6 on 2026-06-25 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def normalize_existing_tickets(apps, schema_editor):
    Ticket = apps.get_model("tickets", "Ticket")
    TicketHistory = apps.get_model("tickets", "TicketHistory")
    now = timezone.now()

    for ticket in Ticket.objects.all():
        changed_fields = []

        if ticket.priority == "urgent":
            ticket.priority = "critical"
            changed_fields.append("priority")

        if ticket.status == "closed" and ticket.closed_at is None:
            ticket.closed_at = now
            changed_fields.append("closed_at")

        if changed_fields:
            ticket.save(update_fields=changed_fields)

        TicketHistory.objects.get_or_create(
            ticket_id=ticket.id,
            from_status="",
            to_status=ticket.status,
            defaults={"note": "Initial imported state"},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_history_entries', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Ticket history',
                'verbose_name_plural': 'Ticket history',
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(normalize_existing_tickets, migrations.RunPython.noop),
    ]
